config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'restaurants#top'
  resources :restaurants do
    get 'search', 'ranking', on: :collection
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  resources :messages, only: [:index, :create]
  resources :users, only: [:show, :edit, :update]
  post '/users/guest_sign_in', to: 'users#test_user'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant

  validates_uniqueness_of :restaurant_id, scope: :user_id
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_restaurant

  def create
    @like = Like.new(user_id: current_user.id, restaurant_id: params[:restaurant_id])
    flash.now[:alert] = 'いいねに失敗しました' unless @like.save
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, restaurant_id: params[:restaurant_id])
    flash.now[:alert] = 'いいねの削除に失敗しました' unless @like.destroy
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if user_signed_in? %>
  <% if current_user.already_liked?(@restaurant) %>
    <%= button_to restaurant_like_path(restaurant_id: @restaurant, id: @restaurant.likes[0].id), method: :delete, remote: true, id:"like-btn-#{@restaurant.id}", class:"liked-btn" do %>
      <i class="fas fa-heart like-heart"></i><div class="like-text">お気に入り解除</div>
    <% end %>
  <% else %>
    <%= button_to restaurant_likes_path(@restaurant), remote: true, id:"like-btn-#{@restaurant.id}", class:"like-btn" do %>
      <i class="far fa-heart like-heart"></i><div class="like-text">お気に入り登録</div>
    <% end %>
  <% end %>
<% end %>

app/views/likes/create.js.erb
$('#like-btn-<%= @restaurant.id %>').html("<%= escape_javascript(render 'likes/like', restaurant: @restaurant) %>");

app/views/likes/destroy.js.erb
$('#like-btn-<%= @restaurant.id %>').html("<%= escape_javascript(render 'likes/like', restaurant: @restaurant) %>");