config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'restaurants#top'
  resources :restaurants do
    get 'search', 'ranking', on: :collection
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  resources :messages, only: [:index, :create]
  resources :users, only: [:show, :edit, :update]
  post '/users/guest_sign_in', to: 'users#test_user'
end

app/models/ambiance.rb
class Ambiance < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'オシャレ' },
    { id: 3, name: '落ち着いた空間' },
    { id: 4, name: '賑やか（宴会向き）' },
    { id: 5, name: '賑やか（子供連れ向き）' }
  ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to       :user
  belongs_to       :restaurant

  validates :content, presence: true
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '寿司・海鮮' },
    { id: 3, name: 'うどん・そば' },
    { id: 4, name: 'ラーメン' },
    { id: 5, name: '焼肉・ステーキ' },
    { id: 6, name: '和食その他' },
    { id: 7, name: 'アジア・エスニック料理' },
    { id: 8, name: 'イタリアン' },
    { id: 9, name: 'フレンチ' },
    { id: 10, name: '居酒屋・バー' },
    { id: 11, name: 'カフェ・スイーツ' },
    { id: 12, name: 'その他' }
  ]
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant

  validates_uniqueness_of :restaurant_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user

  validates :content, presence: true
end

app/models/price.rb
class Price < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '¥' },
    { id: 3, name: '¥¥' },
    { id: 4, name: '¥¥¥' }
  ]
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :genre
  belongs_to_active_hash :ambiance
  belongs_to_active_hash :price

  belongs_to       :user
  has_one_attached :image
  has_many         :comments,                  dependent: :destroy
  has_many         :likes,                     dependent: :destroy
  has_many         :liked_users,               through: :likes, source: :user

  with_options presence: true do
    validates :name
    validates :description
    validates :genre_id
    validates :ambiance_id
    validates :price_id
    validates :image
    # 電話番号はハイフンなし
    validates :tel, format: { with: /\A\d{10}$|^\d{11}\z/, message: 'の入力が正しくありません' }
    validates :address
    validates :opening_hour
    validates :closed
    validates :taste_rate
    validates :price_rate
    validates :service_rate
  end

  with_options numericality: { other_than: 1, message: 'を選択してください' } do
    validates :genre_id
    validates :ambiance_id
    validates :price_id
  end

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def self.search(search)
    if search != ''
      Restaurant.where('name LIKE(?)', "%#{search}%")
                .or(where('description LIKE(?)', "%#{search}%"))
                .or(where('address LIKE(?)', "%#{search}%"))
                .or(where('opening_hour LIKE(?)', "%#{search}%"))
                .or(where('closed LIKE(?)', "%#{search}%"))
    else
      Restaurant.order('created_at DESC')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :restaurants
  has_many :comments,          dependent: :destroy
  has_many :messages,          dependent: :destroy
  has_many :likes,             dependent: :destroy
  has_many :liked_restaurants, through: :likes, source: :restaurant
  has_one_attached :image

  with_options presence: true do
    validates :name,        format: { with: /\A[ぁ-んァ-ン一-龥]/, message: 'の入力が正しくありません' }
    validates :name_kana,   format: { with: /\A[ァ-ヶー－]+\z/, message: 'は全角カタカナで入力してください' }
    validates :employee_id, format: { with: /\A[0-9]+\z/, message: 'は半角で入力してください' }
    # validates :password,    format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'は英数字混合で入力してください' }
  end

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  def already_liked?(restaurant)
    likes.exists?(restaurant_id: restaurant.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :name_kana, :employee_id])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :image])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_item

  def create
    @comment = Comment.new(comment_params)
    @comments = @restaurant.comments.includes(:user).order('created_at DESC')
    if @comment.valid?
      @comment.save
      ActionCable.server.broadcast 'comment_channel', content: @comment, name: @comment.user.name,
                                                      time: @comment.created_at.strftime('%Y/%m/%d %H:%M:%S')
    else
      ActionCable.server.broadcast 'comment_channel', error: 'undefined'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      redirect_to restaurant_path(@restaurant.id)
    else
      flash.now[:alert] = 'コメントの削除に失敗しました'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :image).merge(user_id: current_user.id, restaurant_id: params[:restaurant_id])
  end

  def set_item
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_restaurant

  def create
    @like = Like.new(user_id: current_user.id, restaurant_id: params[:restaurant_id])
    flash.now[:alert] = 'いいねに失敗しました' unless @like.save
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, restaurant_id: params[:restaurant_id])
    flash.now[:alert] = 'いいねの削除に失敗しました' unless @like.destroy
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_item
  before_action :authenticate_user!

  def index
    @message = current_user.messages.new
  end

  def create
    @message = Message.new(message_params)
    if @message.valid?
      @message.save
      ActionCable.server.broadcast 'message_channel', content: @message, name: @message.user.name,
                                                      time: @message.created_at.strftime('%Y/%m/%d %H:%M:%S')
    else
      ActionCable.server.broadcast 'message_channel', error: 'error'
    end
  end

  private

  def message_params
    params.require(:message).permit(:content).merge(user_id: current_user.id)
  end

  def set_item
    @messages = Message.includes(:user).order('created_at ASC')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :test_user
  before_action :set_user

  def show
    @restaurants = current_user.restaurants.order('created_at DESC')
  end

  def edit
  end

  def update
    flash.now[:alert] = '更新に失敗しました' unless @user.update(user_params)
  end

  def test_user
    user = User.find_or_create_by!(email: 'test@example.com') do |user|
      user.name = "テストユーザー"
      user.name_kana = "テストユーザー"
      user.employee_id = "111"
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
    end
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oshiete29826</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
    <script src="https://kit.fontawesome.com/3d325d5779.js" crossorigin="anonymous"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBKhJxnO8KuxjqgRzmg2y3kbnKNuB6cA10" async defer></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/raty/3.0.0/jquery.raty.min.js" integrity="sha512-82+rXsrLf7WAylMdkaH5lWdNXWC0xHUKB41bmUCMICDHy/qpMZqpo4fQlBRJ5h1oSCqFOwKTWC4u2+vR2fblFw==" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_about.html.erb
<%# CSS・・・assets/stylesheets/restaurants/about.css %>
<div class="about-text">
  <p class="about-first-line">
    「おすすめのレストランはありますか？」
  </p>
  <p>
    お客様からのご質問に最適な答えを返すことができていますか？<br>
    「みんなに人気」のレストラン<br>
    「自分が好き」なレストラン<br>
    どちらも魅力的ですが<br>
    「そのお客様にぴったり」のレストランをおすすめできるとより満足度を上げられるかもしれません</p>
  <p class="about-last-line">
    <span class="em-text">O!shi-ete</span>でサービス側の視点を踏まえた<span class="em-text">おいしい</span>お店を<span class="em-text">おしえ</span>合いましょう
  </p>
</div>

app/views/shared/_comment_err.html.erb
<div id='err_container' style='display: none'>
  <ul id="err-messages">
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_comments.html.erb
<h3 class="comments-label">コメント（<%= comments.count %>）</h3>
<!-- コメント１〜３つ目まで -->
<div id='comments'></div>
<% comments.first(3).each do |comment| %>
  <% unless comment.id == nil %>
    <li class="entire-comment">
      <div class="comment-name"><%= comment.user.name %><div>
      <div class="comment-body">
        <%= comment.content %>
        <% if user_signed_in? %>
          <% if comment.user_id == current_user.id || current_user.admin? %>
            <%= link_to restaurant_comment_path(comment.restaurant_id, comment.id), method: :delete, class: "trash-icon" do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <div class="comment-date notes">
        <%= comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
      </div>
    </li>
  <% end %>
<% end %>
<div onclick="obj=document.getElementById('open').style; obj.display=(obj.display=='none')?'block':'none';", class="more">
<a style="cursor:pointer;">さらに表示</a>
</div>

<!-- コメント４つ目以降 -->
<div id="open" style="display:none;clear:both;">
  <% comments.offset(3).each do |comment| %>
    <% unless comment.id == nil %>
      <li class="entire-comment">
        <div class="entier-comment">
          <div class="comment-name"><%= comment.user.name %><div>
          <div class="comment-body">
            <%= comment.content %>
            <% if user_signed_in? %>
              <% if comment.user == current_user || current_user.admin? %>
                <%= link_to restaurant_comment_path(comment.restaurant.id, comment.id), method: :delete, remote: true, class: "trash-icon" do %>
                  <i class="fas fa-trash-alt"></i>
                <% end %>
              <% end %>
            <% end %>
          </div>
          <div class="comment-date notes">
            <%= comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
          </div>
        </div>
      </li>
    <% end %>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul class="err-messages">
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_hamburger.html.erb
<%# CSS・・・assets/stylesheets/shared/hamburger.css %>
<nav class="hamburger-menu">
  <ul>
    <li><%= link_to 'HOME', root_path %></li>
    <li><%= link_to 'ABOUT', root_path(anchor: 'about') %></li>
    <li><%= link_to 'HOW TO', root_path(anchor: 'how_to') %></li>
    <li><%= link_to 'EAT', restaurants_path %></li>
    <li><%= link_to 'CHAT', messages_path(anchor: 'bottom') %></li>
    <% if user_signed_in? %>
      <li><%= link_to 'マイページ', user_path(current_user) %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to '簡単ログイン', users_guest_sign_in_path, method: :post %></li>
      <li><%= link_to 'ログイン', new_user_session_path %></li>
      <li><%= link_to '新規登録', new_user_registration_path %></li>
    <% end %>
    <li class="close"><span>閉じる</span></li>
  </ul>
</nav>

<%# ハンバーガーメニューボタン%>
<div class="hamburger-background">
  <div class="hamburger", id="hamburger">
    <span></span>
    <%# ハンバーガーメニューの表示／非表示 %>
    <script>
      $(function() {
        const hum = $('#hamburger, .close')
        const nav = $('.hamburger-menu')
        hum.on('click', function(){
          nav.toggleClass('toggle');
        });
      });
    </script>
  </div>
</div>
<%# ハンバーガーここまで %>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='site-logo'>
    <h1 class="logo-h1">
      <%= link_to image_tag("logo.png", class: "logo-icon"), "/" %>
    </h1>
    <ul class='lists-right'>
      <%# ログインの有無で表示が変わる%>
      <% if user_signed_in? %>
        <% if current_user.image.attached?%>
          <li>
            <%= link_to user_path(current_user) do %>
              <%= image_tag current_user.image, class:"header-prof-img"%>
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to image_tag("mypage.png", class: "right-list mypage-icon"), user_path(current_user) %>
          </li>
        <% end %>
        <li class="logout-btn"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "right-list login-btn" %></li>
      <% else %>
        <li><%= link_to '簡単ログイン', users_guest_sign_in_path, method: :post, class: "right-list register-btn" %></li>
        <li><%= link_to 'ログイン', new_user_session_path, class: "right-list login-btn" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "right-list register-btn" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_how_to.html.erb
<div class="howto-parent">
  <div class="howto-child">
    <span class="box-title">Ｐｏｓｔ</span>
    <div class="post-child howto-title">投稿機能</div>
    <div class="post-child">
      <%= image_tag 'post-img.png', class:"howto-img" %>
    </div>
    <div class="post-child howto-text">お客様におすすめしたい飲食店を見つけたら<span class="howto-em-text">EAT</span>ページからみんなに<span class="howto-em-text">共有</span>してみよう</div>
  </div>
  <div class="howto-child">
    <span class="box-title">Ｃｏｍｍｅｎｔ</span>
    <div class="post-child howto-title">コメント機能</div>
    <div class="post-child">
      <%= image_tag 'comment-img.png', class:"howto-img" %>
    </div>
    <div class="post-child howto-text">行ったことのあるお店が投稿されていたらお店の詳細ページから口コミを<span class="howto-em-text">コメント</span>してみよう</div>
  </div>
  <div class="howto-child">
    <span class="box-title">Ｃｈａｔ</span>
    <div class="post-child howto-title">チャット機能</div>
    <div class="post-child">
      <%= image_tag 'chat-img.png', class:"howto-img" %>
    </div>
    <div class="post-child howto-text">
      <p>目当ての条件に当てはまる投稿がまだなかった？</p>
      <p>そんな時は<span class="howto-em-text">チャット</span>でみんなから情報を募ってみよう！</p>
    </div>
  </div>
</div>

app/views/shared/_index_left.html.erb
<div class="restaurant-new-form">
    <%= link_to '投稿する', new_restaurant_path, class:"r-new-form-btn" %>
</div>
<div class="search-parent">
  <div class="search-form">
    <%= form_with(url: search_restaurants_path, local: true, method: :get) do |form| %>
    <%= form.text_field :keyword, placeholder: "検索する", class: "search-input" %>
    <%= form.submit "", class: "search-btn" %><i class="fas fa-search"></i>
    <% end %>
  </div>
</div>

app/views/shared/_index_right.html.erb
<% @restaurants.each do |restaurant| %>
  <li>
    <div class="restaurant-lists">
      <div class="restaurant-image">
        <%= link_to restaurant_path(restaurant.id) do %>
          <%= image_tag restaurant.image, class:"restaurant-img" %>
        <% end %>
      </div>
      <div class="restaurant-info">
        <h3 class="restaurant-name">
          <%= link_to restaurant.name, restaurant_path(restaurant.id) %>
        </h3>
        <div class="index-like">
          <i class="fas fa-heart"></i> <%= restaurant.liked_users.count %>
        </div>
        <div class="restaurant-genre">
          <div class="genre-name">
            <i class="fas fa-utensils"></i><%= restaurant.genre.name %>
          </div>
        </div>
        <div class="restaurant-closed"><%= "定休日：#{restaurant.closed}" %></div>
      </div>
    </div>
  </li>
<% end %>

app/views/shared/_liked_index_right.html.erb
<% @user.liked_restaurants.each do |restaurant| %>
  <li>
    <div class="restaurant-lists">
      <div class="restaurant-image">
        <%= link_to restaurant_path(restaurant.id) do %>
          <%= image_tag restaurant.image, class:"restaurant-img" %>
        <% end %>
      </div>
      <div class="restaurant-info">
        <h3 class="restaurant-name">
          <%= link_to restaurant.name, restaurant_path(restaurant.id) %>
        </h3>
        <div class="restaurant-genre">
          <div class="genre-name">
            <i class="fas fa-utensils"></i><%= restaurant.genre.name %>
          </div>
        </div>
        <div class="restaurant-closed"><%= "定休日：#{restaurant.closed}" %></div>
      </div>
    </div>
  </li>
<% end %>

app/views/shared/_message.html.erb
<%# CSS・・・assets/stylesheets/messages/message.css %>
<% @messages.each do |message| %>
  <% if message.user_id == current_user.id %>
  <div class="my-message-parent", id="my_messages">
    <div class="fake-my-messages">
      <%= render 'shared/msg_content', message: message %>
    </div>
    <div class="my-messages">
      <%= render 'shared/msg_content', message: message %>
    </div>
  </div>
  <% else %>
  <div class="my-message-parent", id="your_messages">
    <div class="your-messages">
      <%= render 'shared/msg_content', message: message %>
    </div>
    <div class="fake-your-messages">
      <%= render 'shared/msg_content', message: message %>
    </div>
  </div>
  <% end %>
<% end %>

app/views/shared/_msg_content.html.erb
<div class="chat-sender"><%= message.user.name %></div>
<div class="chat-text"><%= simple_format(h message.content) %></div>
<div class="chat-date"><%= message.created_at.strftime('%Y/%m/%d %H:%M') %></div>

app/views/shared/_second-header.html.erb
<%# CSS・・・assets/stylesheets/shared/second-header.css %>
<ul class='lists-center'>
  <li><%= link_to 'HOME', root_path, class: "center-list" %></li>
  <li><%= link_to 'ABOUT', root_path(anchor: 'about'), class: "center-list" %></li>
  <li><%= link_to 'HOW TO', root_path(anchor: 'how_to'), class: "center-list" %></li>
  <li><%= link_to 'EAT', restaurants_path, class: "center-list" %></li>
  <li><%= link_to 'CHAT', messages_path(anchor: 'bottom'), class: "center-list" %></li>
</ul>