config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'restaurants#top'
  resources :restaurants do
    get 'search', 'ranking', on: :collection
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  resources :messages, only: [:index, :create]
  resources :users, only: [:show, :edit, :update]
  post '/users/guest_sign_in', to: 'users#test_user'
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :genre
  belongs_to_active_hash :ambiance
  belongs_to_active_hash :price

  belongs_to       :user
  has_one_attached :image
  has_many         :comments,                  dependent: :destroy
  has_many         :likes,                     dependent: :destroy
  has_many         :liked_users,               through: :likes, source: :user

  with_options presence: true do
    validates :name
    validates :description
    validates :genre_id
    validates :ambiance_id
    validates :price_id
    validates :image
    # 電話番号はハイフンなし
    validates :tel, format: { with: /\A\d{10}$|^\d{11}\z/, message: 'の入力が正しくありません' }
    validates :address
    validates :opening_hour
    validates :closed
    validates :taste_rate
    validates :price_rate
    validates :service_rate
  end

  with_options numericality: { other_than: 1, message: 'を選択してください' } do
    validates :genre_id
    validates :ambiance_id
    validates :price_id
  end

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def self.search(search)
    if search != ''
      Restaurant.where('name LIKE(?)', "%#{search}%")
                .or(where('description LIKE(?)', "%#{search}%"))
                .or(where('address LIKE(?)', "%#{search}%"))
                .or(where('opening_hour LIKE(?)', "%#{search}%"))
                .or(where('closed LIKE(?)', "%#{search}%"))
    else
      Restaurant.order('created_at DESC')
    end
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search, :top]
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.order('created_at DESC')
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.valid?
      @restaurant.save
      redirect_to restaurants_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @restaurant.comments.includes(:user).order('created_at DESC')
    @like = Like.new
  end

  def edit
    render :show unless current_user == @restaurant.user || current_user.admin?
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path
    else
      render :edit
    end
  end

  def destroy
    if @restaurant.destroy
      redirect_to restaurants_path
    else
      render :show
    end
  end

  def search
    @restaurants = Restaurant.search(params[:keyword])
  end

  def ranking
    @restaurants = Restaurant.all.sort { |a, b| b.liked_users.count <=> a.liked_users.count }
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :genre_id, :ambiance_id, :price_id, :tel, :address, :opening_hour,
                                       :closed, :image, :webpage, :parking, :others, :taste_rate, :price_rate, :service_rate)
          .merge(user_id: current_user.id)
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/edit.html.erb
<%# CSS・・・assets/stylesheets/restaurants/new.css %>
<div class="registration-background">
  <div class="post-panel">

    <%= form_with model: @restaurant, class: 'registration-main', local: true do |f| %>
      <h1>編集する</h1>

      <%# エラーメッセージ表示 %>
      <%= render "shared/error_messages", model: @restaurant %>

      <%# 写真選択 %>
      <div class="form-group">
        <div>
          <label class="info-text">写真</label>
          <div class="notes">外観やメニュー、料理の写真などを共有しよう</div>
        </div>
        <%= image_tag @restaurant.image, class:"restaurant-img" if @restaurant.image.present? %>
        <div id="restaurant-image-list"></div>
        <%= f.file_field :image, class:"image-form" %>
      </div>

      <%# 店名 %>
      <div class="form-group">
        <div>
          <label class="info-text">お店の名前</label>
        </div>
        <%= f.text_field :name, class:"form-space" %>
      </div>

      <%# 評価 %>
      <div class="form-group" id="taste_star">
        <%= f.label :taste_rate,'おいしさ　', class:'col-md-3 col-form-label' %>
        <%= f.hidden_field :taste_rate, id: :review_star %>
      </div>

      <script>
        $(document).ready(function() {
          $('#taste_star').raty({
            size     : 15,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            scoreName: 'restaurant[taste_rate]',
            half: true,
          });
        });
      </script>  

      <div class="form-group" id="price_star">
        <%= f.label :price_rate,'値段　　　', class:'col-md-3 col-form-label' %>
        <%= f.hidden_field :price_rate, id: :review_star %>
      </div>

      <script>
        $('#price_star').raty({
          size     : 15,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          scoreName: 'restaurant[price_rate]',
          half: true,
        });
      </script>  

      <div class="form-group" id="service_star">
        <%= f.label :service_rate,'接客　　　', class:'col-md-3 col-form-label' %>
        <%= f.hidden_field :service_rate, id: :review_star %>
      </div>

      <script>
        $('#service_star').raty({
          size     : 15,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          scoreName: 'restaurant[service_rate]',
          half: true,
        });
      </script>  

      <%# カテゴリー %>
      <div class="form-group">
        <div>
          <label class="info-text">カテゴリー</label>
        </div>
        <div class="select-wrap">
          <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        </div>
      </div>

      <%# 雰囲気 %>
      <div class="form-group">
        <div>
          <label class="info-text">お店の雰囲気</label>
        </div>
        <div class="select-wrap">
          <%= f.collection_select(:ambiance_id, Ambiance.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        </div>
      </div>

      <%# 価格帯 %>
      <div class="form-group">
        <div>
          <label class="info-text">価格帯</label>
        </div>
        <div class="select-wrap">
          <%= f.collection_select(:price_id, Price.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        </div>
      </div>

      <%# 店舗説明 %>
      <div class="form-group">
        <div>
          <label class="info-text">キャプション</label>
          <div class="notes">味の感想やサービスの質、客層などを共有しよう</div>
        </div>
        <%= f.text_area :description, class:"form-space-large" %>
      </div>

      <%# 電話番号 %>
      <div class="form-group">
        <div>
          <label class="info-text">お店の電話番号</label>
          <div class="notes">ハイフンなしの半角入力</div>
        </div>
        <%= f.text_field :tel, class:"form-space" %>
      </div>

      <%# 住所 %>
      <div class="form-group">
        <div>
          <label class="info-text">お店の住所</label>
        </div>
        <%= f.text_field :address, class:"form-space" %>
      </div>

      <%# 営業時間 %>
      <div class="form-group">
        <div>
          <label class="info-text">営業時間</label>
        </div>
        <%= f.text_area :opening_hour, class:"form-space-large" %>
      </div>

      <%# 定休日 %>
      <div class="form-group">
        <div>
          <label class="info-text">定休日</label>
        </div>
        <%= f.text_area :closed, class:"form-space-large" %>
      </div>

      <%# ホームページ %>
      <div class="form-group">
        <div>
          <label class="info-text">ホームページ</label>
        </div>
        <%= f.text_area :webpage, class:"form-space" %>
      </div>

      <%# 駐車場 %>
      <div class="form-group">
        <div>
          <label class="info-text">駐車場</label>
        </div>
        <%= f.text_area :parking, class:"form-space" %>
      </div>

      <%# 備考 %>
      <div class="form-group">
        <div>
          <label class="info-text">備考</label>
        </div>
        <%= f.text_area :others, class:"form-space-large" %>
      </div>

      <div class="actions">
        <%= f.submit "投稿する", class:"register-btn" %>
      </div>

      <div class="actions">
        <%=link_to 'もどる', restaurant_path(@restaurant.id), class:"back-btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/index.html.erb
<%# CSS・・・assets/stylesheets/restaurants/index.css %>
<div class="pc-menu">
  <%= render 'shared/header' %>
  <%= render 'shared/second-header' %>
</div>
<div class="restaurant-page">
<%# 左のエリア %>
  <div class="left-side-restaurant">
    <%= render 'shared/index_left' %>
  </div>

  <%# 右のエリア %>
  <div class="right-side-restaurant">
  <%= render 'shared/hamburger' %>
    <h2 class="right-side-header">カフェ・レストラン一覧</h2>
    <div class="pc-index-hidden">
      <%= render 'shared/index_left' %>
    </div>
    <div class="like-ranks"><%= link_to "いいね順", ranking_restaurants_path %></div>
    <%= render 'shared/index_right' %>
  </div>
</div>

app/views/restaurants/new.html.erb
<%# CSS・・・assets/stylesheets/restaurants/new.css %>
<div class="registration-background">
  <div class="post-panel">

    <%= form_with model: @restaurant, class: 'registration-main', local: true do |f| %>
      <h1 class="restaurant-post-headline">おいしいを教える</h1>

      <%# エラーメッセージ表示 %>
      <%= render "shared/error_messages", model: @restaurant %>

      <%# 写真選択 %>
      <div class="form-group">
        <div>
          <label class="info-text">写真</label>
          <div class="notes">外観やメニュー、料理の写真などを共有しよう</div>
        </div>
        <%= f.file_field :image, class:"image-form" %>
        <div id="restaurant-image-list"></div>
      </div>

      <%# 店名 %>
      <div class="form-group">
        <div>
          <label class="info-text">お店の名前</label>
        </div>
        <%= f.text_field :name, class:"form-space" %>
      </div>

      <%# 評価 %>
      <div class="form-group" id="taste_star">
        <%= f.label :taste_rate,'おいしさ　', class:'col-md-3 col-form-label' %>
        <%= f.hidden_field :taste_rate, id: :review_star_taste %>
      </div>

      <script>
        $(document).ready(function() {
          $('#taste_star').raty({
            size     : 15,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            scoreName: 'restaurant[taste_rate]',
            half: true,
          });
        });
      </script>  

      <div class="form-group" id="price_star">
        <%= f.label :price_rate,'値段　　　', class:'col-md-3 col-form-label' %>
        <%= f.hidden_field :price_rate, id: :review_star_price %>
      </div>

      <script>
        $('#price_star').raty({
          size     : 15,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          scoreName: 'restaurant[price_rate]',
          half: true,
        });
      </script>  

      <div class="form-group" id="service_star">
        <%= f.label :service_rate,'接客　　　', class:'col-md-3 col-form-label' %>
        <%= f.hidden_field :service_rate, id: :review_star_service %>
      </div>

      <script>
        $('#service_star').raty({
          size     : 15,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          scoreName: 'restaurant[service_rate]',
          half: true,
        });
      </script>  

      <%# カテゴリー %>
      <div class="form-group genre-form">
        <div>
          <label class="info-text">カテゴリー</label>
        </div>
        <div class="select-wrap">
          <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"item-genre"}) %>
        </div>
      </div>

      <%# 雰囲気 %>
      <div class="form-group">
        <div>
          <label class="info-text">お店の雰囲気</label>
        </div>
        <div class="select-wrap">
          <%= f.collection_select(:ambiance_id, Ambiance.all, :id, :name, {}, {class:"select-box", id:"item-ambiance"}) %>
        </div>
      </div>

      <%# 価格帯 %>
      <div class="form-group">
        <div>
          <label class="info-text">価格帯</label>
        </div>
        <div class="select-wrap">
          <%= f.collection_select(:price_id, Price.all, :id, :name, {}, {class:"select-box", id:"item-price"}) %>
        </div>
      </div>

      <%# 店舗説明 %>
      <div class="form-group">
        <div>
          <label class="info-text">キャプション</label>
          <div class="notes">味の感想やサービスの質、客層などを共有しよう</div>
        </div>
        <%= f.text_area :description, class:"form-space-large" %>
      </div>

      <%# 電話番号 %>
      <div class="form-group">
        <div>
          <label class="info-text">お店の電話番号</label>
          <div class="notes">ハイフンなしの半角入力</div>
        </div>
        <%= f.text_field :tel, class:"form-space" %>
      </div>

      <%# 住所 %>
      <div class="form-group">
        <div>
          <label class="info-text">お店の住所</label>
        </div>
        <%= f.text_field :address, class:"form-space" %>
      </div>

      <%# 営業時間 %>
      <div class="form-group">
        <div>
          <label class="info-text">営業時間</label>
        </div>
        <%= f.text_area :opening_hour, class:"form-space-large" %>
      </div>

      <%# 定休日 %>
      <div class="form-group">
        <div>
          <label class="info-text">定休日</label>
        </div>
        <%= f.text_area :closed, class:"form-space-large" %>
      </div>

      <%# ホームページ %>
      <div class="form-group">
        <div>
          <label class="info-text">ホームページ</label>
        </div>
        <%= f.text_area :webpage, class:"form-space" %>
      </div>

      <%# 駐車場 %>
      <div class="form-group">
        <div>
          <label class="info-text">駐車場</label>
        </div>
        <%= f.text_area :parking, class:"form-space" %>
      </div>

      <%# 備考 %>
      <div class="form-group">
        <div>
          <label class="info-text">備考</label>
        </div>
        <%= f.text_area :others, class:"form-space-large" %>
      </div>

      <div class="actions">
        <%= f.submit "投稿する", class:"register-btn" %>
      </div>

      <div class="actions">
        <%=link_to 'もどる', restaurants_path, class:"notes" %>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/ranking.html.erb
<%# CSS・・・assets/stylesheets/restaurants/index.css %>
<div class="pc-menu">
  <%= render 'shared/header' %>
  <%= render 'shared/second-header' %>
</div>

<div class="restaurant-page">
<%# 左のエリア %>
  <div class="left-side-restaurant">
    <%= render 'shared/index_left' %>
  </div>

  <%# 右のエリア %>
  <div class="right-side-restaurant">
  <%= render 'shared/hamburger' %>
    <h2 class="right-side-header">カフェ・レストラン一覧</h2>
    <div class="pc-index-hidden">
      <%= render 'shared/index_left' %>
    </div>
    <div class="like-ranks"><%= link_to "新着順", restaurants_path %></div>
    <%= render 'shared/index_right' %>
  </div>
</div>

app/views/restaurants/search.html.erb
<div class="pc-menu">
  <%= render 'shared/header' %>
  <%= render 'shared/second-header' %>
</div>

<div class="restaurant-page">
<%# 左のエリア %>
  <div class="left-side-restaurant">
    <%= render 'shared/index_left' %>
  </div>

  <%# 右のエリア %>
  <div class="right-side-restaurant">
  <%= render 'shared/hamburger' %>
  <h2 class="right-side-header">『<%= params[:keyword] %>』の検索結果</h2>
  <div class="pc-index-hidden">
    <%= render 'shared/index_left' %>
  </div>
    <%= render 'shared/index_right' %>
  </div>
</div>

app/views/restaurants/show.html.erb
<%# CSS・・・assets/stylesheets/restaurants/show.css %>
<div class="pc-menu">
  <%= render 'shared/header' %>
  <%= render 'shared/second-header' %>
</div>

<div class="restaurant-show-page">

  <div class="show-header">
    <p class="show-name"><%= @restaurant.name %></p>
    <div class="show-header-child">
      <% if user_signed_in? %>
        <% if current_user.id == @restaurant.user_id || current_user.admin? %>
          <%= link_to '編集する', edit_restaurant_path(@restaurant.id), class:"s-edit-btn" %>
          <%= link_to '削除する', restaurant_path(@restaurant.id), method: :delete, class:"s-edit-btn", data: {confirm: "削除しますか？"} %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="show-child">
    <div class="show-grand-child">
      <div class="first-grand-child">
        <div class="show-list">
          <ul class="show-sammary">
            <li class="show-title">
              ジャンル：
            </li>
            <li class="show-content">
              <%= @restaurant.genre.name %>
            </li>
          </ul>
          <ul class="show-sammary">
            <li class="show-title">
              雰囲気：
            </li>
            <li class="show-content">
              <%= @restaurant.ambiance.name %>
            </li>
          </ul>
          <ul class="show-sammary">
            <li class="show-title">
              予算：
            </li>
            <li class="show-content">
              <%= @restaurant.price.name %>
            </li>
          </ul>
        </div>

        <div class="show-rates">
          <%# 味の星評価 %>
          <div id="taste_star-<%= @restaurant.id %>", class="rate-child"><div class="rate-child-text">おいしさ：</div></div>
          <script>
          $('#taste_star-<%= @restaurant.id %>').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            readOnly: true,
            score: <%= @restaurant.taste_rate %>
          });
          </script>

          <%# 値段の星評価 %>
          <div id="price_star-<%= @restaurant.id %>", class="rate-child"><div class="rate-child-text">値段：</div></div>
          <script>
          $('#price_star-<%= @restaurant.id %>').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            readOnly: true,
            score: <%= @restaurant.price_rate %>
          });
          </script>

          <%# 接客の星評価 %>
          <div id="service_star-<%= @restaurant.id %>", class="rate-child"><div class="rate-child-text">接客：</div></div>
          <script>
          $('#service_star-<%= @restaurant.id %>').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            readOnly: true,
            score: <%= @restaurant.service_rate %>
          });
          </script>  
        </div>

        <div class="show-main-body">
          <%= link_to @restaurant.image, "data-lightbox" => @restaurant.image do %>
            <%= image_tag @restaurant.image.variant(resize: '600x600'), class:"show-image" %>
          <% end %>
          <p class="show-post-user"><i class="fas fa-user-edit"></i><%= @restaurant.user.name %></p>
          <div class="show-description"><%= simple_format(h @restaurant.description) %></div>
          <%# いいねボタン %>
          <div id="like-btn-<%= @restaurant.id %>", class="like">
            <%= render 'likes/like', restaurant: @restaurant %>
          </div>

          <%# 店舗情報エリア %>
          <table class="info-table">
            <caption><span class="caption-restaurant-name"><%= "#{@restaurant.name}" %></span>の店舗情報</caption>
            <div class="table-space">
            <tr>
              <th class="genre-table">ジャンル</th><td><%= @restaurant.genre.name %></td>
            </tr>
            <tr>
              <th>雰囲気</th><td><%= @restaurant.ambiance.name %></td>
            </tr>
            <tr>
              <th class="hour-table">営業時間</th><td><%= @restaurant.opening_hour %></td>
            </tr>
            <tr>
              <th class="closed-table">定休日</th><td><%= @restaurant.closed %></td>
            </tr>
            <tr>
              <th class="genre-address">住所</th>
              <td><%= @restaurant.address %><br>
                  <div class="map" id="map"></div>
                  <%= javascript_tag do %>
                    window.address = <%= raw @restaurant.address.to_json %>
                  <% end %>
              </td>
            </tr>
            <tr>
              <th class="genre-tel">電話番号</th><td><%= @restaurant.tel %></td>
            </tr>
            <tr>
              <th class="genre-web">ホームページ</th><td><%= @restaurant.webpage %></td>
            </tr>
            <tr>
              <th class="genre-parking">駐車場</th><td><%= @restaurant.parking %></td>
            </tr>
            <tr>
              <th class="genre-others">備考</th><td><%= @restaurant.others %></td>
            </tr>
            </div>
          </table>
        </div>
      </div>
    </div>
    <div class="show-grand-child">
      <!-- コメント一覧表示 -->
      <ul>
        <li id="comments_area">
          <%= render 'shared/comments', comments: @comments %>
        </li>
      </ul>
      <!-- コメント入力欄 -->
      <% if current_user %>
        <div class="comment-space">
          <p class="posts-label">コメントを投稿する</p>
          <%= form_with url: restaurant_comments_path(@restaurant.id), model: [@restaurant, @comment], class:"comment-form" do |f| %>
            <%= f.text_area :content, placeholder: "コメント", class:"comment-field", id:"comment_text" %>
            <%= f.submit "コメントする", class: "comment-btn" %>
          <% end %>
        </div>
      <% else %>
        <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/top.html.erb
<%# CSS・・・assets/stylesheets/restaurants/top.css %>
<div class="pc-menu">
  <%= render 'shared/header' %>
  <%= render 'shared/second-header' %>
</div>

<nav class="hamburger-menu">
  <ul>
    <li><%= link_to 'HOME', root_path %></li>
    <li><%= link_to 'ABOUT', root_path(anchor: 'about') %></li>
    <li><%= link_to 'HOW TO', root_path(anchor: 'how_to') %></li>
    <li><%= link_to 'EAT', restaurants_path %></li>
    <li><%= link_to 'CHAT', messages_path(anchor: 'bottom') %></li>
    <% if user_signed_in? %>
      <li><%= link_to 'マイページ', user_path(current_user) %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to '簡単ログイン', users_guest_sign_in_path, method: :post %></li>
      <li><%= link_to 'ログイン', new_user_session_path %></li>
      <li><%= link_to '新規登録', new_user_registration_path %></li>
    <% end %>
    <li class="close"><span>閉じる</span></li>
  </ul>
</nav>

<div class="top-container">
  <div class="above-main">
    <div class="top-head-text">O!SHI-ete</div>
    <%= image_tag 'top-header.jpg', class:"top-head-image" %>
  </div>
  <%# ハンバーガーメニューボタン%>
  <div class="hamburger-top", id="hamburger">
    <span></span>
    <%# ハンバーガーメニューの表示／非表示 %>
    <script>
      $(function() {
        const hum = $('#hamburger, .close')
        const nav = $('.hamburger-menu')
        hum.on('click', function(){
          nav.toggleClass('toggle');
        });
      });
    </script>
  </div>
  <%# ハンバーガーここまで %>
  <div class="index-main">
    <%# CSS・・・assets/stylesheets/restaurants/about.css %>
    <div class="about", id="about">
      <h1 class="about-headline">O!SHI-eteとは？</h1>
      <%= image_tag 'dish.png', class:"about-icon" %>
      <%= render 'shared/about' %>
    </div>
    <div class="top-middle-image-position">
      <%= image_tag 'toppage.jpg', class:"top-middle-image"%>
    </div>
    <div class="how-to", id="how_to">
      <h1 class="howto-head"><span class="howto-headline">　使い方　</span><i class="fas fa-highlighter"></i></h1>
      <%= render 'shared/how_to' %>
    </div>
    <div id="back_to_top"><a href="#top", class="back-to-top-btn">TOP</a></div>
  </div>
</div>